name: CalendarApp
options:
  bundleIdPrefix: com.andrewspruce
  deploymentTarget:
    macOS: "13.0"
targets:
  CalendarApp:
    type: application
    platform: macOS
    sources:
      - CalendarApp
    info:
      path: CalendarApp/Info.plist
      properties:
        CFBundleDisplayName: Calendar
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleName: $(PRODUCT_NAME)
        CFBundlePackageType: APPL
        CFBundleShortVersionString: "1.0"
        CFBundleVersion: "1"
        LSMinimumSystemVersion: $(MACOSX_DEPLOYMENT_TARGET)
        NSCalendarsUsageDescription: "This app needs access to your calendars to display and manage events."
        NSRemindersUsageDescription: "This app needs access to your reminders to display and manage tasks."
        NSHumanReadableCopyright: ""
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.andrewspruce.CalendarApp
      INFOPLIST_FILE: CalendarApp/Info.plist
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      ENABLE_HARDENED_RUNTIME: YES
      COMBINE_HIDPI_IMAGES: YES
